tf.argmax与numpy的argmax函数作用一样，作用都是取行或者列的最大值的位置

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
classes = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1]])
logits = np.array([[0.9,0.1,0],
                  [0.6,0.8,0.9],
                  [0,0,1]])

In [3]:
np.argmax(logits,axis=1)

array([0, 2, 2])

In [4]:
classes[np.argmax(logits,axis=1)]

array([[1, 0, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [5]:
 # 判断是否与预测相同
np.equal(np.argmax(logits,axis=1),np.argmax(classes,axis=1))

array([ True, False,  True])

In [6]:
# tensorflow
correct_prediction = tf.equal(tf.argmax(logits,1),tf.argmax(classes,1))

In [8]:
# 上面代码给出一组bool值，把布尔值转换成浮点数
accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))
with tf.Session() as sess:
    print(sess.run(accuracy))

0.6666667
