https://mp.weixin.qq.com/s/lSoMYQW4F49VALGHjlXKfQ

In [1]:
import tensorflow as tf

In [2]:
tf.constant(1)  # 创建一个整型张量

<tf.Tensor: id=0, shape=(), dtype=int32, numpy=1>

In [3]:
tf.constant(1.)  # 创建一个浮点型张量

<tf.Tensor: id=1, shape=(), dtype=float32, numpy=1.0>

In [4]:
tf.constant(2., dtype=tf.double)  # 创建的同时指定数据类型

<tf.Tensor: id=2, shape=(), dtype=float64, numpy=2.0>

In [5]:

tf.constant([[1.,2.,3.],[4.,5.,6.]])  # 通过传入一个list参数创建

<tf.Tensor: id=3, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [6]:
# convert_to_tensor()方法
import numpy as np

In [7]:
tf.convert_to_tensor(np.ones([2,3]))

<tf.Tensor: id=4, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [8]:
tf.constant([[1.,2.,3.],[4.,5.,6.]])  # 通过传入一个list参数创建

<tf.Tensor: id=5, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [9]:
# 2.3创建元素为指定值的tensor,tf.ones() tf.zeros_like() tf.ones_like()
a = tf.zeros([2,3,3])
a

<tf.Tensor: id=8, shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [10]:
# fill()
tf.fill([2,3],5)

<tf.Tensor: id=11, shape=(2, 3), dtype=int32, numpy=
array([[5, 5, 5],
       [5, 5, 5]])>

In [11]:
# 2.4随机初始化
tf.random.normal([2,3],mean=1,stddev=1) # （1）从指定正态分布中随机取值：tf.random.normal()

<tf.Tensor: id=17, shape=(2, 3), dtype=float32, numpy=
array([[ 3.1181767,  1.3984854, -0.1648717],
       [ 1.2165109,  2.85012  ,  1.319372 ]], dtype=float32)>

In [12]:
tf.random.truncated_normal([2, 3], mean=1, stddev=1) #（1）从指定正态分布中随机取值：tf.random.normal()

<tf.Tensor: id=23, shape=(2, 3), dtype=float32, numpy=
array([[-0.99802756,  1.3702276 ,  0.78938186],
       [ 0.1720981 ,  0.71339643,  1.0667598 ]], dtype=float32)>

In [13]:
tf.random.uniform([2, 3], minval=1, maxval=2) # （3）从指定均匀分布中随机取值：tf.random.uniform()

<tf.Tensor: id=30, shape=(2, 3), dtype=float32, numpy=
array([[1.3564968, 1.2618505, 1.0016094],
       [1.859125 , 1.8522097, 1.3919953]], dtype=float32)>

In [15]:
# 索引
a = tf.convert_to_tensor(np.arange(80).reshape(2,2,4,5))
a

<tf.Tensor: id=31, shape=(2, 2, 4, 5), dtype=int32, numpy=
array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]],


       [[[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]],

        [[60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74],
         [75, 76, 77, 78, 79]]]])>